from bs4 import BeautifulSoup
html_doc = """
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" >
<head id="Head1"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Trang thông tin dành cho tín đồ công nghệ | GenK.vn</title><meta name="description" content="GenK là Website uy tín số 1 Việt Nam cung cấp cho bạn những thông tin mới nhất về công nghệ và thế giới Internet,tin tức sản phẩm cong nghe mới." /><meta name="generator" content="VCCorp.vn" /><meta name="copyright" content="Công ty cổ phần Truyền Thông Việt Nam - Vccorp" /><meta name="author" content="VCCorp.vn" /><meta name="news_keywords" content="máy tính, điện thoại, tablet, laptop, mobile, facebook, internet, nokia, apple, android, windows, mac, phần mềm, thủ thuật, photoshop, ram,công nghệ, cong nghe" /><meta http-equiv="audience" content="General" /><meta http-equiv="Content-Language" content="vi" /><meta name="Language" content="vi" /><meta name="resource-type" content="Document" /><meta name="distribution" content="Global" /><meta name="revisit-after" content="1 days" /><meta name="google-site-verification" content="toa0juwM2J5NpYj1sW5s_gNp7Fz9AjMmOhcDP9-6_64" /><meta name="verify-v1" content="Ymm4FWh55niAwGdM/AxjsBSNSsp14TAweQOVQaYMOKY=" /><meta name="page-topic" content="Trang thông tin dành cho tín đồ công nghệ" /><meta name="RATING" content="GENERAL" /><meta name="robots" content="index,follow" /><meta name="Googlebot" content="index,follow,archive" /><meta property="og:locale" content="vi_VN" /><meta property="fb:app_id" content="180276625471433" /><meta property="fb:admins" content="1133617216" /><meta property="fb:pages" content="186426311375329" /><meta id="fbTitle" itemprop="headline" property="og:title" content="Trang thông tin dành cho tín đồ công nghệ" /><meta id="fbDescription" property="og:description" content="GenK là Website uy tín số 1 Việt Nam cung cấp cho bạn những thông tin mới nhất về công nghệ và thế giới Internet,tin tức sản phẩm cong nghe mới." /><meta id="fbImage" itemprop="thumbnailUrl" property="og:image" content="http://genknews.genkcdn.vn/web_images/genk-1200x630.jpg" /><meta id="fbUrl" property="og:url" content="http://genk.vn/" /><meta id="fbSiteName" property="og:site_name" content="genk.vn" /><meta id="fbType" property="og:type" content="article" /><meta name="alexaVerifyID" content="zZ7ti1umNJzQmTM9Kanp-wnQh5M" /><meta id="fbImg" itemprop="image" content="http://genknews.genkcdn.vn/web_images/genk-1200x630.jpg" /><meta name="apple-mobile-web-app-title" content="GenK" /><meta name="application-name" content="GenK" /><link rel="shortcut icon" href="http://genknews.genkcdn.vn/web_images/genk32.png" type="image/png" />
"""
soup = BeautifulSoup(html_doc, 'html.parser')

with open("abc.html", 'w') as f:
	f.write(soup.prettify())
